# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-21 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinf',
            options={'ordering': ('id',), 'verbose_name': 'Usuario Empleado', 'verbose_name_plural': 'Usuarios Empleados'},
        ),
    ]
