# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-21 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20170621_0255'),
        ('userInf', '0002_auto_20170621_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBoleta', models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 21, 3, 19, 38, 756000), editable=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInf.Userinf')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Propietario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TipoBoleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='tipoBoleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.TipoBoleta'),
        ),
    ]
