# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0007_auto_20170621_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='dateBoleta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 21, 19, 26, 7, 901000), editable=False),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Propietario'),
        ),
    ]
