# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-21 06:37
from __future__ import unicode_literals

import cliente.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=225)),
                ('nombre', models.CharField(max_length=225)),
                ('fech_nacimiento', models.DateField(blank=True)),
                ('especie', models.CharField(blank=True, max_length=225)),
                ('estado_interno', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'Campo vacio!', 'invalid': 'Dato invalido', 'null': 'Campo vacio!'}, max_length=225, validators=[cliente.models.validar_str, cliente.models.validate_letra_M])),
                ('ape_pat', models.CharField(error_messages={'blank': 'Campo vacio!', 'invalid': 'Dato invalido', 'null': 'Campo vacio!'}, max_length=225, validators=[cliente.models.validar_str, cliente.models.validate_letra_M])),
                ('ape_mat', models.CharField(error_messages={'blank': 'Campo vacio!', 'invalid': 'Dato invalido', 'null': 'Campo vacio!'}, max_length=225, validators=[cliente.models.validar_str, cliente.models.validate_letra_M])),
                ('DNI', models.CharField(max_length=8, unique=True, validators=[cliente.models.validate_length_DNI, cliente.models.validate_type_Value])),
                ('direccion_domi', models.CharField(blank=True, max_length=225, null=True)),
                ('cell', models.CharField(max_length=9, unique=True, validators=[cliente.models.validate_length_cell, cliente.models.validate_type_Value])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='Propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Propietario'),
        ),
    ]
