# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-21 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('cliente', '0001_initial'),
        ('userInf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInf.Userinf'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Propietario'),
        ),
    ]
