# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_auto_20170621_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dateConsulta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 21, 19, 26, 7, 898000), editable=False),
        ),
    ]
