# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 01:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userInf', '0002_auto_20170621_0255'),
        ('cliente', '0005_auto_20170621_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHistorial', models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 21, 20, 10, 16, 857000), editable=False)),
                ('descripcion', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInf.Userinf')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Mascota')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
