# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-22 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='dateHistorial',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 21, 20, 14, 16, 34000), editable=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
